---
driver:
  name: ec2
  aws_ssh_key_id: aws-ssh
  region: us-east-1
  availability_zone: us-east-1d
  require_chef_omnibus: true
  security_group_ids:
    - sg-8d8b73f5

transport:
  ssh_key: /Users/nathgood/Keys/aws-ssh.pem
  connection_timeout: 30
  connection_retries: 5
  username: ec2-user

provisioner:
  name: chef_solo

platforms:
  - name: amazon
    driver:
      image_id: ami-d4f7ddbe
      instance_type: m3.medium

suites:
  - name: default
    run_list:
      - recipe[cfn-jenkins-server::default]
    attributes:
